tablekeep/apps/base/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import TemplateView

from tablekeep.apps.base import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^locatie/', include('tablekeep.apps.locations.urls')),
    url(r'^bs/$', TemplateView.as_view(template_name='base/bscode.html')),

    # settings
    url(r'^setari/$', views.SettingsView.as_view(), name='settings'),
    url(r'^setari/parola/$', views.PasswordChangeView.as_view(),
        name='settings_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += patterns(
        '', url(r'^__debug__/', include(debug_toolbar.urls)),
    )

tablekeep/apps/locations/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # employee index
    url(r'^menu/$', views.EmployeeIndexView.as_view(),
        name='employee_index'),

    # location
    url(r'^(?P<pk>\d+)/configurare/$', views.LocationConfigView.as_view(),
        name='location_config'),
    url(r'^(?P<pk>\d+)/layout/$', views.LocationLayoutView.as_view(),
        name='location_layout'),
    url(r'^(?P<pk>\d+)/$', views.LocationDetailView.as_view(),
        name='location_detail'),


    url(r'^$', views.LocationListView.as_view(),
        name='location_list'),
    url(r'^adauga/$', views.LocationCreateView.as_view(),
        name='location_create'),
    url(r'^editeaza/(?P<pk>\d+)/$', views.LocationUpdateView.as_view(),
        name='location_update'),

    # sector
    # no need for location_id in below urls since we have the pk of a sector
    url(r'^sector/(?P<pk>\d+)/layout/$', views.SectorLayoutView.as_view(),
        name='sector_layout'),
    url(r'^sector/(?P<pk>\d+)/$', views.SectorDetailView.as_view(),
        name='sector_detail'),
    url(r'^(?P<pk>\d+)/sector/create/$', views.SectorCreateView.as_view(),
        name='sector_create'),

    # all sectors for a specific location
    url(r'^(?P<location_id>\d+)/sector/list/$', views.SectorListView.as_view(),
        name='sector_list'),

    # table
    url(r'^table/(?P<pk>\d+)/chair/plus/$',
        views.TableChairView.as_view(operator='plus'),
        name='table_chair_plus'),

    url(r'^table/(?P<pk>\d+)/chair/minus/$',
        views.TableChairView.as_view(operator='minus'),
        name='table_chair_minus'),

    url(r'^sector/(?P<pk>\d+)/table/create/$', views.TableCreateView.as_view(),
        name='table_create'),

    url(r'^table/(?P<pk>\d+)/delete/$',
        views.TableDeleteView.as_view(), name='table_delete'),

    url(r'^table/(?P<table_id>\d+)/reserve/$',  # reservation
        views.TableReserveView.as_view(), name='table_reserve'),

    url(r'^table/(?P<table_id>\d+)/free/$',  # unreservation
        views.TableFreeView.as_view(), name='table_free'),

    # tableclient
    url(r'^(?P<location_id>\d+)/tableclient/list/$',
        views.TableClientListView.as_view(), name='tableclient_list'),

    # booking
    url(r'^(?P<location_id>\d+)/booking/list/$',
        views.BookingListView.as_view(), name='booking_list'),
    url(r'^(?P<location_id>\d+)/booking/create/$',
        views.BookingCreateView.as_view(), name='booking_create'),
    url(r'^(?P<location_id>\d+)/booking/slot/$',
        views.BookingSlotView.as_view(), name='booking_slot'),
]

tablekeep/apps/locations/models.py
import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import render_to_string

from swampdragon.models import SelfPublishModel
from .serializers import TableSerializer, SectorSerializer


class Employee(models.Model):
    user = models.OneToOneField(User)
    ROLE = (
        (1, 'Hostess'),
        (2, 'Chelner'),
        (3, 'Sef sala'),
        (4, 'CEO'),
    )
    role = models.IntegerField(choices=ROLE, default=1)

    location = models.ForeignKey('Location')
    can_configure_location = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    @property
    def name(self):
        return self.user.get_full_name() or self.user.username


def location_upload_to(instance, filename):
    return 'location/logo/{id}/{filename}'.format(
        id=instance.id,
        filename=filename
    )


class Location(models.Model):
    not_required = {'blank': True, 'null': True}

    name = models.CharField(max_length=512)
    address = models.CharField(max_length=512)
    logo = models.ImageField(upload_to=location_upload_to, **not_required)
    rank = models.IntegerField(default=0, help_text='Special ordering')

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.name

    @property
    def logo_url(self):
        if not self.logo:
            return '{}css/images/image_placeholder_100.png'.format(
                settings.STATIC_URL
            )
        return self.logo.url

    def get_absolute_url(self):
        return reverse('location_detail', args=[self.id])

    def get_layout_url(self):
        return reverse('location_layout', args=[self.id])

    def get_config_url(self):
        return reverse('location_config', args=[self.id])


class Sector(SelfPublishModel, models.Model):
    serializer_class = SectorSerializer

    location = models.ForeignKey(Location)
    number = models.PositiveIntegerField()

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Employee)

    class Meta:
        ordering = ['number']
        unique_together = ('location', 'number')

    def __unicode__(self):
        return u'%s - Sector %s' % (self.location, self.number)

    def get_absolute_url(self):
        return reverse('sector_detail', args=[self.location.id, self.id])

    @property
    def is_arranged(self):
        return self.table_set.exclude(layout='').count() != 0

    @property
    def free_tables(self):
        return self.table_set.filter(reservation__isnull=True).count()


class Table(SelfPublishModel, models.Model):
    serializer_class = TableSerializer

    sector = models.ForeignKey(Sector)
    number = models.PositiveIntegerField()

    chair_count = models.PositiveIntegerField()

    layout = models.CharField(
        max_length=256, default='', blank=True,
        help_text='The attr style of the table - if set with jquery ui')

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Employee)

    reservation = models.ForeignKey(
        'TableClient', blank=True, null=True, related_name='reservation',
        on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ['number']
        unique_together = ('sector', 'number')

    def __unicode__(self):
        return u'%s - masa %s' % (self.sector, self.number)

    def get_absolute_url(self):
        # add a hash tag to highlight it once in sector detail
        return '{base_url}#tbl-{hash_tag}'.format(
            base_url=reverse('sector_detail', args=[self.sector.id]),
            hash_tag=self.id
        )

    @property
    def is_reserved(self):
        return self.reservation is not None

    @property
    def chair_range(self):
        return range(self.chair_count)

    def get_one_tbl_html(self):
        return render_to_string('locations/include/one_tbl.html', {
            'table': self
        })

    def get_one_sector_tbl_html(self):
        return render_to_string('locations/include/one_sector_tbl.html', {
            'table': self
        })

    def upcoming_bookings(self, gap=settings.LOCATIONS_BOOKING_GAP):
        now = datetime.datetime.now()
        end = now + datetime.timedelta(0, gap)
        return self.booking_set.filter(
            location=self.sector.location,
            timestamp__range=[now, end]
        ).order_by('timestamp')


class TableClient(models.Model):
    table = models.ForeignKey(Table)
    client = models.ForeignKey('Client')

    start = models.DateTimeField()
    end = models.DateTimeField(blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('Employee')

    def __unicode__(self):
        return u'%s - %s' % (self.table, self.client)


class Client(models.Model):
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=16, default='', blank=True)
    email = models.EmailField(max_length=64, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Employee)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        super(Client, self).save(*args, **kwargs)


class Booking(models.Model):
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=16)
    email = models.EmailField(max_length=64, null=True, blank=True)

    person_count = models.PositiveIntegerField()
    timestamp = models.DateTimeField()  # help_text='For what date and time')

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Employee)

    location = models.ForeignKey(Location)
    table = models.ForeignKey(Table)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        super(Booking, self).save(*args, **kwargs)

tablekeep/apps/locations/forms.py
from django import forms
from django.conf import settings

from collections import OrderedDict

from tablekeep.apps.locations.models import Employee, Location, Sector, Table, Booking
from tablekeep.apps.base.forms import FunkyForm


class LocationForm(FunkyForm, forms.ModelForm):
    created_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput())
    modified_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput(),
        required=False)

    class Meta:
        fields = '__all__'
        model = Location


class SectorForm(FunkyForm, forms.ModelForm):
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(), widget=forms.HiddenInput())
    created_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput())
    modified_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput(),
        required=False)

    class Meta:
        fields = '__all__'
        model = Sector


class TableForm(FunkyForm, forms.ModelForm):
    sector = forms.ModelChoiceField(
        queryset=Sector.objects.all(), widget=forms.HiddenInput())
    created_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput())
    number = forms.IntegerField(widget=forms.HiddenInput())
    chair_count = forms.IntegerField(label='Numar scaune', min_value=1, max_value=10)

    class Meta:
        exclude = ('reservation', 'layout')
        model = Table


class BookingForm(FunkyForm, forms.ModelForm):
    created_by = forms.ModelChoiceField(
        queryset=Employee.objects.all(), widget=forms.HiddenInput())
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(), widget=forms.HiddenInput())
    table = forms.ModelChoiceField(
        queryset=Table.objects.all(), widget=forms.HiddenInput())
    timestamp = forms.DateTimeField(input_formats=settings.DATETIME_INPUT_FORMAT)

    class Meta:
        fields = '__all__'
        model = Booking

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)

        label_map = {
            'person_count': 'Numar persoane',
            'phone': 'Telefon',
            'name': 'Nume',
            'timestamp': 'Ora si data rezervarii',
        }

        for name, field in self.fields.items():
            label = label_map.get(name, None)
            if label is not None:
                field.label = label

            if field.required:
                field.widget.attrs.update({'required': 'required'}) 

            field.widget.attrs.update({'autocomplete': 'off'})


BookingForm.base_fields = OrderedDict(                                            
    (k, BookingForm.base_fields[k])                                         
    for k in ['timestamp', 'person_count', 'name', 'phone', 'email', 'table', 'created_by', 'location']
) 


from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, UserChangeForm
)
from django.contrib.auth.models import User
# MOCKUP 


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', )


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.uf = UserCreateForm(*args, **kwargs)

        super(EmployeeCreateForm, self).__init__(*args, **kwargs)

        self.fields.update(self.uf.fields)
        self.initial.update(self.uf.initial)

        self.fields['rank'].widget = forms.HiddenInput()
        self.fields['user'].widget = forms.HiddenInput()
        self.fields['user'].required = False  # set in save below
        self.fields['email'].required = True

        # set labels
        for field, label in self.label_map.items():
            self.fields.get(field).label = label

        # add gumby classes to prettify form
        for name, field in self.fields.items():
            if not hasattr(field, 'choices'):
                field.widget.attrs.update({'class': 'input'})
            if name in ['services', 'resume']:
                field.widget.attrs.update({
                    'class': 'input textarea',
                    'rows': 5
                })
            field.widget.attrs.update({'placeholder': field.label})
            # mark required fields
            if field.required:
                field.widget.attrs.update({'data-required': 'required'})

    @property
    def label_map(self):
        return {
            'username': 'Utilizator',
            'display_name': 'Nume profil',
        }

    def is_valid(self):
        """
        Updates the errors with suer form errors so both forms get validated.
        """
        self.errors.update(self.uf.errors)
        return super(EmployeeCreateForm, self).is_valid()

    def save(self, *args, **kwargs):
        """
        Saves the user and attaches it to the employee. Returns the employee
        """
        user = self.uf.save(*args, **kwargs)
        employee = super(EmployeeCreateForm, self).save(*args, commit=False, **kwargs)
        employee.user = user
        employee.save()
        return employee

tablekeep/apps/locations/templates/locations/booking_form.html
{% extends "base/base.html" %}

{% block js %}
    {{ block.super }}

    <script type="text/javascript">
        Booking = {
            init: function(){
                Utils.create_datetime_picker("#id_timestamp");
                Utils.init_tooltips();
                this.handle_booking_slot();
                this.handle_form_submit();
                $("#id_timestamp").focus();
            },
            handle_booking_slot: function(){
                var send_ajax = function(container, timestamp, chair_count){
                    if (timestamp && chair_count){
                        container.html("");
                        $.ajax({
                            url: $("form").data("filter-url"),
                            data: {
                                timestamp: timestamp,
                                chair_count: chair_count
                            },
                            success: function(response){
                                container.html(response);
                                // reset table
                                $("#id_table").val("");
                                container.find(".take-slot.best-slot:first").click();
                            }
                        })
                    }
                }
                $("#id_timestamp").change(function(event){
                    var timestamp = $(this).val();
                    var chair_count = $("#id_person_count").val();
                    var container = $("#bookingFilterWrap");
                    send_ajax(container, timestamp, chair_count);
                });
                $("#id_person_count").change(function(event){
                    var chair_count = $(this).val();
                    var timestamp = $("#id_timestamp").val();
                    var container = $("#bookingFilterWrap");
                    send_ajax(container, timestamp, chair_count);
                });

                $("body").on("click", ".take-slot", function(event){
                    event.preventDefault();
                    var self = $(this);
                    // visual
                    $(".slot").removeClass("selected");
                    self.find(".slot").addClass("selected");

                    // set table
                    $("#id_table").val(self.data("table-id"));

                    // reset timestamp if something else is chosen
                    $("#id_timestamp").val(self.data("timestamp"));
                });
            },
            handle_form_submit: function(){
                $("form").submit(function(event){
                    var self = $(this);
                    if (self.find("#id_table").val() == ""){
                        $("#table-message").text("Mai intai trebuie sa selectezi o masa si un interval orar, dand click pe un patratel verde.")
                        return false;
                    }
                    return true;
                });
            }
        }
        $(function(){
            Booking.init();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row white well">
        <a href="{% url 'booking_list' request.user.employee.location.id %}" class="pull-left btn btn-default ttip" data-toggle="tooltip" title="Inapoi">
            <span class="glyphicon glyphicon-arrow-left"></span>
        </a>
        <h5 class="pull-left">Rezervare</h5>
    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="white well row">
                <form action="./" method="POST" data-filter-url="{% url 'booking_slot' location_id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div id="table-message" class="errorlist">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success pull-left">Adauga</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-9">
            <div id="bookingFilterWrap">
            </div>
        </div>
    </div>
{% endblock %}

tablekeep/apps/locations/templates/locations/index.html
{% extends "base/base.html" %}

{% block beadcrumbs %}
    <div class="clearfix white well">
        <div class="col-md-6">
        </div>
        <div class="col-md-6">
        </div>
    </div>
{% endblock %}

{% block content %}
    <h5 class="text-center">
        {{ request.user.employee.name }}
        <span class="square label label-primary">{{ request.user.employee.get_role_display }}</span>
        x mese servite
    </h5>
    <hr>
    <div id="account-menu">
        <div class="row">
            <div class="col-xs-6">
                <a class="huge btn btn-default" href="{{ request.user.employee.location.get_absolute_url }}">
                    <span class="glyphicon glyphicon-map-marker"></span>
                    Locatie
                </a>
            </div>
            <div class="col-xs-6">
                <a class="huge btn btn-default" href="{% url 'booking_list' request.user.employee.location.id %}">
                    <span class="glyphicon glyphicon-list"></span>
                    Rezervari
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
                {% if request.user.employee.can_configure_location %}
                    <a class="huge btn btn-default" href="{{ request.user.employee.location.get_config_url }}">
                        <span class="glyphicon glyphicon-cog"></span>
                        Configurare <span class="hidden-xs">locatie</span>
                    </a>
                {% endif %}
            </div>
            <div class="col-xs-6">
                <a class="huge btn btn-default" href="{% url 'tableclient_list' request.user.employee.location.id %}">
                    <span class="glyphicon glyphicon-user"></span>
                    Clienti
                </a>
            </div>
        </div>
    </div>
{% endblock %}

tablekeep/apps/locations/templates/locations/location_config.html
{% extends "base/base.html" %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        LocationConfig = {
            init: function(){
                this.submit_button = $("button[type='submit']");
                this.build_location();
            },
            build_location: function(){
                var that = this;
                $("#build-sectors").click(function(event){
                    event.preventDefault();
                    var self = $(this);
                    var sector_count_input = $("#id_sector_count");
                    var count = sector_count_input.val();
                    if (count == 0){
                        self.closest(".panel-body").find(".form-control").addClass("has-error");
                    } else {
                        self.closest(".panel-body").find(".form-control").removeClass("has-error");

                        var container = $("#sectorWrap");
                        container.empty();

                        for (i = 1; i <= count; i++) {
                            var clone = $("#sector-clone").clone();
                            clone.find(".panel-title").find(".counter").text(i);
                            clone.find("input.sector_number").val(i);
                            clone.find("a.build-tables").attr("data-sector-number", i);
                            clone.show();
                            clone.removeAttr("id");
                            container.append(clone);
                        }
                    }
                });

                $("body").on("click", ".build-tables", function(event){
                    event.preventDefault();
                    var self = $(this);
                    var table_count_input = self.closest(".panel-body").find(".table_count");
                    var count = table_count_input.val();
                    if (count == 0){
                        self.closest(".panel-body").find(".form-control").addClass("has-error");
                    } else {
                        self.closest(".panel-body").find(".form-control").removeClass("has-error");

                        var sector_number = self.attr("data-sector-number");
                        var container = self.closest(".sector").find(".tableWrap");
                        container.empty();

                        for (i = 1; i <= count; i++) {
                            var clone = $("#table-clone").clone();
                            clone.removeAttr("id");
                            clone.find(".panel-title").find(".counter").text(i);
                            clone.find("input.table_number").val(i);
                            clone.find("input.sector_number").val(sector_number);
                            clone.show();
                            container.append(clone);
                        }

                        // at least one sector with tables is defined show submit button
                        that.submit_button.show();
                        
                        // scroll the page
                        Utils.scroll_animate(self.closest(".sector"), -70, 500);
                    }
                });

                $("#locationConfigForm").submit(function(event){
                    event.preventDefault();
                    var self = $(this);

                    // emulate one submit action allowance
                    if (!self.hasClass("submitting")){
                        self.addClass("submitting");
                        var location_data = []
                        $(".table:visible").each(function(index, item){
                            var table = $(item);
                            location_data.push({
                                sector: table.find("input.sector_number").val(),
                                table: table.find("input.table_number").val(),
                                chair_count: table.find("input.chair_count").val()
                            })
                        });
                        $.ajax({
                            url: self.attr("action"),
                            method: self.attr("method"),
                            data: $.param({
                                csrfmiddlewaretoken: self.find("input[name='csrfmiddlewaretoken']").val(),
                                location_data: JSON.stringify(location_data)
                            }),
                            success: function(response){
                                location.href = response;
                                self.removeClass("submitting");
                            }
                        });
                    }
                });
            },
        }
        $(function(){
            LocationConfig.init();
        });
    </script>
{% endblock %}

{% block content %}
    <div id="locationConfigWrap">
        <hr>
        <div class="clearfix">
            <h5> Configureaza {{ location }} </h5>
            <blockquote>
                1. Adauga numarul de sectoare.
                <br>
                2. Adauga numarul de mese in fiecare sector in parte.
                <br>
                3. Adauga numarul de scaune la fiecare masa in parte.
            </blockquote>
        </div>
        <hr>
        <div id="locationWrap" class="row">
           <div class="panel panel-primary">
               <div class="panel-heading">
                   <h3 class="panel-title">
                       <label for="id_sector_count">
                           {{ location }}
                       </label>
                   </h3>
               </div>
               <div class="panel-body">
                    <div class="form-control">
                        <input id="id_sector_count" type="number" min="0" max="50" name="sector_count" placeholder="Numar sectoare" value="{{ location.sector_set.count|default:"" }}" />
                        <span class="">&nbsp;</span>
                        <a class="btn btn-primary" id="build-sectors" href="#">OK</a>
                    </div>
               </div>
           </div>
        </div>

        <form id="locationConfigForm" action="./" method="POST">
            {% csrf_token %}
            <div id="sectorWrap" class="row">
                {# sector clones get dumped here #}
                {% for sector in location.sector_set.all %}
                    <div class="sector">
                        {% include "locations/include/sector_inner.html" %}
                        <div class="tableWrap row">
                            {% for table in sector.table_set.all %}
                                <div class="table">
                                    {% include "locations/include/table_inner.html" %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="form-control row">
                {# hide the submit button if no sector is created - shown in js above when tables are added for at least one sector #}
                {% if location.sector_set.count %}
                    <button type="submit" class="btn btn-success">Salveaza</button>
                {% else %}
                    <button type="submit" class="btn btn-success" style="display:none;">Salveaza</button>
                {% endif %}
            </div>
        </form>

        <br>
        <br>
        <br>

        {# below two clones are used to initially set up the location #}
        {# when the location is set up - the sectors and tables are displayed above #}
        <div id="sector-clone" class="sector" style="display:none;">
            {% include "locations/include/sector_inner.html" %}
            <div class="tableWrap row">
                {# table clones get dumped here #}
            </div>
        </div>
        <div id="table-clone" class="table" style="display:none;">
            {% include "locations/include/table_inner.html" %}
        </div>
    </div>
{% endblock %}

tablekeep/apps/locations/templates/locations/location_form.html
{% extends "base/base.html" %}


{% block content %}
    <div class="row">
        <h2> Adauga locatie </h2>
        <div class="col-md-6">
            <form action='./' method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Adauga</button>
            </form>
        </div>
    </div>
{% endblock %}

tablekeep/apps/locations/templates/locations/location_layout.html
{% extends "base/base.html" %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        LocationLayout = {
            init: function(){
                // create sector through ajax pulled forms
                Utils.handle_ajax_modals();
            },
        }
        $(function(){
            LocationLayout.init();
        });
    </script>
{% endblock %}

{% block content %}
    <div id="locationLayoutWrap">
        <hr>
        <div class="clearfix">
            <h5 class="pull-left"> Aranjeaza {{ location }} </h5>
            <a href="{% url 'sector_create' location.id %}"
                data-modal-id="#sectorCreateModal"
                class="pull-right pull-modal btn btn-primary ttip"
                data-toggle="tooltip" title="Adauga un sector">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
            <div style="clear:both;"></div>
            <blockquote>
                1. Click pe un sector pentru a-l aranja.
                <br>
                2. Adauga un sector <span class="glyphicon glyphicon-plus"></span>
            </blockquote>
        </div>
        <hr>
        <div id="sectorsWrap" class="clearfix">
            {% for sector in location.sector_set.all %}
                {% include "locations/include/one_sector_layout.html" %}
                {% if forloop.counter|divisibleby:2 %}
                    {# whats included above is set to float left with a 50% width #}
                    <div style="clear:both;"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}